### ISSUE TITLE
Add CI tests using github actions

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#12]
Travis has gotten less reliable and gh actions very fast. Looks like there is nice integration with `usethis`:
https://ropenscilabs.github.io/actions_sandbox/

Other resources
https://github.com/r-lib/actions
https://www.rostrum.blog/2020/08/09/ghactions-pkgs/

**Comment by mccallc** [comment]
github actions now runs R cmd check and codecov on each push as of commit b553ee043440996d782e07932e4b8108a3478b8e, will continue to update workflows as necessary
