### ISSUE TITLE
Add Codecov and testing badge

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#13]
Here's the package for codecov: https://github.com/codecov/example-r the current example is for Travis but the gh_actions documentation looks like it'd be trivial to include

**Comment by mccallc** [comment]
added testing badge to README in commit 38ac39a6e13659a16426336eb9919cb0e7d094c1

**Comment by adam3smith** [comment]
Could you also add a tests passing/failing badge?

**Comment by mccallc** [comment]
yes, definitely will do!
