### ISSUE TITLE
Clean-up pkgdown page for review at Ropensci

### ISSUE THREAD

**Issue by nniiicc** [PESData/awardFindR#16]
The guide for submitting packages to be reviewed by Ropensci recommends publishing a pkgdown site for reviewers. 

https://pkgdown.r-lib.org/ (note you need to install `usethis` first) 

I compiled this locally and then pushed to a `docs` folder... Take a look at the site https://pesdata.github.io/awardFindR/ ... We can clean up by adjusting some of the vignettes metadata if we agree this is helpful for review.

**Comment by mccallc** [comment]
generated all pages in commit 643c929b30799274cf8964fd28a5daaa238c61b3. All documentation should now be available online, vignette included under "getting started"
