### ISSUE TITLE
Error on Ubuntu

### ISSUE THREAD

**Issue by maelle** [PESData/awardFindR#33]
``` r
awardFindR::get_nsf("qualitative", "2019-01-01", "2019-02-25")
#> Error in curl::curl_fetch_memory(url, handle = handle): OpenSSL SSL_read: Connection reset by peer, errno 104
```

<sup>Created on 2022-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mccallc** [comment]
I think this was a temporary server-side error. I am unable to reproduce it. Is it still happening on your end?

**Comment by maelle** [comment]
Indeed, it now works!

Is there a status page for the API that awardFindR could point users too when the API call fails?

**Comment by adam3smith** [comment]
None of the federal APIs have status pages :(
