### ISSUE TITLE
Use of tempfile()

### ISSUE THREAD

**Issue by maelle** [PESData/awardFindR#34]
In https://github.com/ropensci/awardFindR/blob/2c86e2dc10507d3c6ea04a91e7914fb8bd86b134/R/neh.R#L53

a file is created but not deleted which is not optimal (especially for CRAN).

I'd suggest using [`withr::_localtemp_file()`](https://withr.r-lib.org/reference/with_tempfile.html) instead as it will be deleted automatically.

**Comment by mccallc** [comment]
fixed!
