### ISSUE TITLE
Include functions in namespace

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#4]
Add `@export` to all functions so they're included in the `awardsBot` namespace (and thus can be called when installing the packet)

**Comment by mccallc** [comment]
Did this for all the intended user-facing functions in commit c60cd70592db5d6324d350d0916b5953449852af

**Comment by adam3smith** [comment]
(we have to see, but I think package check requires all functions to be exposed -- I've never quite understood the logic there, but if we want this publicly reviewed -- or even just have CI checks running successfully -- we might need to export all)
