### ISSUE TITLE
Choose working defaults for function

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#7]
e.g. `awardsBot(keywords = NULL, sources = NULL, from = NULL, to = NULL)`

OK to leave keywords blank, but let's set sources to all currently available, from to reasonable start date (something covered by most APIs perhaps) and to to today's date).

Also, if we require keywords (which I think we would) not setting a default treats it as required which I think is right here. Apply similarly to other functions

**Comment by mccallc** [comment]
Sources already set to all available by default, and current date default is previous two years (which is pretty heavy on results for some source-query combos, really light for others, but returns ~10k results in total). See https://github.com/PESData/awardsBot/blob/fb72b6f7809408199e2070769a2724d8a61e0083/R/main.R#L41 to line 53

Definitely agree on not having a default keyword

**Comment by adam3smith** [comment]
> Sources already set to all available by default, and current date default is previous two years (which is pretty heavy on results for some source-query combos, really light for others, but returns ~10k results in total). See 

Ah yes, I missed that. Problem is that doing it this way doesn't expose the defaults in the function documentation (which is where I was looking), which I think is useful and also considered best practice

**Comment by mccallc** [comment]
Ah, yes that is a very good point, that would have been where I would have looked too. 

`Sys.Date()` as a default ending date, and Jan 1 2019 as a default starting date?

**Comment by adam3smith** [comment]
Yes, that's good for date, thanks

**Comment by mccallc** [comment]
These defaults included as of commit 7664e9bdd2b8660b9bc33d10d27607c2d52be5f0, documentation should reflect that too
