### ISSUE TITLE
Documentation examples: Make minimal or set to don't test

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#8]
Package check runs all examples in function documentation by default. As a good pratice, let's make these examples as untaxing on the APIs as possible (i.e specific terms, short date ranges). Where that's not possible or desirable use `dontrun{}` or `donttest{}` as per https://stackoverflow.com/a/44997778/1483360

**Comment by mccallc** [comment]
Experimented with a few queries to find ones that pulled minimal results but still got at least one for APIs. More API-intensive queries were still shown in examples but put into `\dontrun{}` blocks. These were implemented in commit 7664e9bdd2b8660b9bc33d10d27607c2d52be5f0
