### ISSUE TITLE
Remove duplicates in output DFs

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#9]
For NSF there are unique IDs, not sure for the others

**Comment by mccallc** [comment]
Each source has their own ID schema that I've preserved in the output DFs. I implemented a straight duplicate check of the ID field which drops duplicates and merges the keyword field so it's easier to see which keywords pick up what. implemented in commit e1fddb5a4559b8ddfb73b1613da013ed47f1a17c
